# Hive catalog for C++ worker
connector.name=hive-hadoop2
hive.metastore.uri=thrift://hive-metastore-presto:9083
hive.config.resources=/etc/presto/core-site.xml

# GCS Support
hive.gcs.json-key-file-path=/etc/presto/gcs-key.json
