# Iceberg catalog for C++ worker
connector.name=iceberg
hive.metastore.uri=thrift://hive-metastore-presto:9083
hive.config.resources=/etc/presto/core-site.xml
iceberg.file-format=PARQUET

# GCS Support
hive.gcs.json-key-file-path=/etc/presto/gcs-key.json
